# Menggunakan PHP 8.3 FPM sebagai base image
FROM php:8.3-fpm

# Set working directory di dalam container
WORKDIR /var/www/html

RUN apt-get update && apt-get install -y \
    curl zip unzip git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install pdo pdo_mysql

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy source code Laravel ke dalam container
COPY src/citizen-complaint-portal/ /var/www/html

# Install dependensi Laravel
RUN composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist

# Set permission untuk Laravel
RUN chmod -R 775 storage bootstrap/cache \
    && chown -R www-data:www-data /var/www/html

# Expose port PHP-FPM
EXPOSE 9000

# Jalankan PHP-FPM sebagai perintah default
CMD ["php-fpm"]
